### PR TITLE
Use LLVM

### PR DESCRIPTION
**Pull request by jakelee8**

### CODE REVIEW

**Review by jtescher — APPROVED** [review]

**Comment by jakelee8** [comment]
This change increases build times by ~100s

**Comment by jtescher** [comment]
Hm would maybe be interesting to see comparative `cargo build --timings` output?

**Comment by jakelee8** [comment]
Actually, the Docker workflow uses the previously built `ghcr.io/bitskico/rust-sdk:latest` image to build dependencies

**Comment by jakelee8** [comment]
~9% faster

```
time docker build --no-cache .

# ghcr.io/bitskico/rust-sdk
 => [builder 2/2] RUN --mount=target=.     --mount=type=cach  89.5s
0.42s user 0.42s system 0% cpu 1:31.49 total
 => [builder 2/2] RUN --mount=target=.     --mount=type=cach  88.8s
0.43s user 0.45s system 0% cpu 1:30.74 total
 => [builder 2/2] RUN --mount=target=.     --mount=type=cach  90.3s
0.44s user 0.45s system 0% cpu 1:32.13 total

# ghcr.io/bitskico/rust-sdk:pr-8
 => [builder 2/2] RUN --mount=target=.     --mount=type=cach  81.7s
0.45s user 0.47s system 0% cpu 1:38.79 total
 => [builder 2/2] RUN --mount=target=.     --mount=type=cach  83.4s
0.42s user 0.46s system 1% cpu 1:25.89 total
 => [builder 2/2] RUN --mount=target=.     --mount=type=cach  81.6s
0.43s user 0.45s system 1% cpu 1:24.25 total```

**Pull request merged**
